# -*- coding: utf-8 -*-
"""protoptyp3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/abhinavvsunil/31f6a696de494db9072ca1d6a02b4f87/protoptyp3.ipynb
"""

import zipfile

zip_path = "/archive (8).zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("stocks")

print("Extraction completed")

from google.colab import drive
drive.mount('/content/drive')

import os

print(os.listdir("stocks/US_Stocks"))

import pandas as pd
import numpy as np

stock_name = "apple_stock.csv"

df = pd.read_csv(f"stocks/US_Stocks/{stock_name}")

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date")

print(df.head())

# Log return
df["log_return"] = np.log(df["Close"] / df["Close"].shift(1))

# Volatility
df["volatility"] = df["log_return"].rolling(20).std()

# Moving averages
df["MA20"] = df["Close"].rolling(20).mean()
df["MA50"] = df["Close"].rolling(50).mean()

df = df.dropna()

print(df.tail())

from sklearn.preprocessing import MinMaxScaler

features = ["Close","volatility","MA20","MA50"]

scaler = MinMaxScaler()

scaled = scaler.fit_transform(df[features])

sequence = 60

X = []
y = []

for i in range(sequence, len(scaled)):
    X.append(scaled[i-sequence:i])
    y.append(scaled[i,0])

X = np.array(X)
y = np.array(y)

print(X.shape, y.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(X.shape[1],X.shape[2])),
    Dropout(0.2),
    LSTM(32),
    Dropout(0.2),
    Dense(1)
])

model.compile(
    optimizer="adam",
    loss="mse"
)

model.fit(
    X,
    y,
    epochs=10,
    batch_size=32
)

future_steps = 30
mc_runs = 10

last_sequence = X[-1]

predictions = []

for _ in range(mc_runs):

    seq = last_sequence.copy()

    future = []

    for i in range(future_steps):

        pred = model(seq.reshape(1,seq.shape[0],seq.shape[1]), training=True)

        future.append(pred.numpy()[0][0])

        seq = np.vstack((seq[1:], seq[-1]))

    predictions.append(future)

predictions = np.array(predictions)

mean_forecast = predictions.mean(axis=0)

lower = np.percentile(predictions, 2.5, axis=0)

upper = np.percentile(predictions, 97.5, axis=0)

# Convert forecast back to real price scale

forecast_prices = scaler.inverse_transform(
    np.column_stack((mean_forecast,
                     np.zeros_like(mean_forecast),
                     np.zeros_like(mean_forecast),
                     np.zeros_like(mean_forecast)))
)[:,0]

lower_prices = scaler.inverse_transform(
    np.column_stack((lower,
                     np.zeros_like(lower),
                     np.zeros_like(lower),
                     np.zeros_like(lower)))
)[:,0]

upper_prices = scaler.inverse_transform(
    np.column_stack((upper,
                     np.zeros_like(upper),
                     np.zeros_like(upper),
                     np.zeros_like(upper)))
)[:,0]

future_days = range(len(df), len(df)+30)

plt.figure(figsize=(10,5))

plt.plot(df["Close"].values, label="Historical")

plt.plot(future_days, forecast_prices, label="Forecast")

plt.fill_between(
    future_days,
    lower_prices,
    upper_prices,
    alpha=0.3,
    label="95% Confidence Interval"
)

plt.legend()
plt.title("30 Day Stock Forecast")
plt.show()

import numpy as np

# Daily volatility
daily_volatility = df["log_return"].std()

# Annualized volatility
annual_volatility = daily_volatility * np.sqrt(252)

# 30-day expected volatility
volatility_30day = daily_volatility * np.sqrt(30)

print("Daily volatility:", daily_volatility)
print("30-day expected volatility:", volatility_30day)
print("Annual volatility:", annual_volatility)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

plt.plot(df["Date"], df["volatility"])

plt.title("Rolling Volatility (20-day)")
plt.xlabel("Date")
plt.ylabel("Volatility")

plt.show()

forecast_price = mean_forecast[-1]

lower_ci = lower[-1]

upper_ci = upper[-1]

print("30-Day Forecast Price:", forecast_price)
print("Confidence Interval:", lower_ci, "-", upper_ci)
print("Expected 30-Day Volatility:", volatility_30day)

company_map = {
    "apple":"apple_stock.csv",
    "amazon":"amazon_stock.csv",
    "microsoft":"microsoft_stock.csv",
    "nvidia":"nvidia_stock.csv",
    "tesla":"tesla_stock.csv",
    "google":"google_stock.csv"
}

def ask_finsearch(question):

    q = question.lower()

    for company in company_map:

        if company in q:

            print("Company detected:", company)

            print("\nForecast summary:")

            print("Predicted 30-day price:", forecast_price)

            print("Confidence interval:", lower_ci, "-", upper_ci)

            print("Expected volatility:", volatility_30day)

            return

    print("Company not recognized")

ask_finsearch("What is the 30 day outlook for apple?")

# Convert forecast values back to real prices

temp = np.zeros((len(mean_forecast), 4))
temp[:,0] = mean_forecast
forecast_prices = scaler.inverse_transform(temp)[:,0]

temp[:,0] = lower
lower_prices = scaler.inverse_transform(temp)[:,0]

temp[:,0] = upper
upper_prices = scaler.inverse_transform(temp)[:,0]

volatility_percent = volatility_30day * 100

def ask_finsearch(question):

    company_map = {
        "amazon": "amazon_stock.csv",
        "amerisource": "AmerisourceBergen_Corp_stock.csv",
        "apple": "apple_stock.csv",
        "berkshire": "berkshire_hathaway_stock.csv",
        "cvs": "CVS_health_corporation_stock.csv",
        "exxon": "exxon_mobil_stock.csv",
        "google": "google_stock.csv",
        "johnson": "johnson_and_johnson_stock.csv",
        "mckesson": "McKesson_corporation_stock.csv",
        "meta": "meta_stock.csv",
        "microsoft": "microsoft_stock.csv",
        "nvidia": "nvidia_stock.csv",
        "tesla": "tesla_stock.csv",
        "united": "united_health_group_stock.csv",
        "visa": "visa_stock.csv",
        "walmart": "walmart_stock.csv"
    }
    q = question.lower()

    company = None
    file_name = None

    for c in company_map:
        if c in q:
            company = c
            file_name = company_map[c]
            break

    if company is None:
        return "Company not recognized."

    # Load company dataset
    df = pd.read_csv(f"stocks/US_Stocks/{file_name}")

    df["Date"] = pd.to_datetime(df["Date"])
    df = df.sort_values("Date")

    # Feature engineering
    df["log_return"] = np.log(df["Close"] / df["Close"].shift(1))
    df["volatility"] = df["log_return"].rolling(20).std()
    df["MA20"] = df["Close"].rolling(20).mean()
    df["MA50"] = df["Close"].rolling(50).mean()

    df = df.dropna()

    # Simple forecast proxy (use last price as baseline)
    last_price = df["Close"].iloc[-1]

    forecast_price = last_price * 1.02
    lower_ci = last_price * 0.95
    upper_ci = last_price * 1.08

    volatility_percent = df["volatility"].iloc[-1] * 100

    if volatility_percent < 10:
        risk = "low"
    elif volatility_percent < 20:
        risk = "moderate"
    else:
        risk = "high"

    explanation = f"""
{company.title()} stock is forecasted to trade around ${forecast_price:.2f} over the next 30 days.

The expected price range is between ${lower_ci:.2f} and ${upper_ci:.2f}, suggesting potential fluctuations.

The predicted volatility is {volatility_percent:.2f}%, indicating {risk} short-term risk.

Overall, the outlook suggests moderate market movement while maintaining the current trend.
"""

    return explanation

ask_finsearch("What is the 30 day outlook for apple?")